### PR TITLE
travis: upgrade to Python 3.7

### PR DESCRIPTION
**Pull request by yoursunny**
Python 2 will reach EOL on 01 JAN 2020.

### CODE REVIEW

**Comment by yoursunny** [comment]
Build log: https://travis-ci.com/yoursunny/CI-temp/builds/125087494
(with branch restriction and after_success removed)

**Comment by yoursunny** [comment]
@cawka can you review?

**Comment by cawka** [comment]
Can you change the commit message to indicate that this upgrade is for documentation build. Otherwise, it can be confusing.

**Comment by yoursunny** [comment]
Commit message has been updated. Use "rebase merge" to ensure the commit message (rather than PR title) appears in git.

**Comment by yoursunny** [comment]
@cawka can you review?

**Pull request merged**
